#!/usr/bin/expect

set timeout 10
set host [lindex $argv 0]
set port [lindex $argv 1]
set username [lindex $argv 2]
set password [lindex $argv 3]

spawn ssh -p $port $username@$host
expect {
    "*assword:"
    {
        send "$password\n"
    }
}
expect "Last login*"
interact

